import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F4F9',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 20,
    marginTop: 0,
    height: '100%',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#004AAD',
    marginBottom: 20,
    marginTop: 40,
    fontFamily: 'sans-serif',
  },
  searchInput: {
    height: 45,
    width: '100%',
    borderColor: '#004AAD',
    borderWidth: 1.5,
    paddingHorizontal: 10,
    marginBottom: 20,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    padding: 10,
    width: '90%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    backgroundColor: '#E6F7FF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 3,
    minHeight: 100,
  },
  fill: {
    flex: 1,
    marginRight: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '60%', 
    marginTop: 5,
  },

  buttonSpacing: {
    width: 5, 
  },
  button: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#004AAD',
    borderRadius: 8,
    padding: 8,
    marginBottom: 2,
    width: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    transition: 'all 0.3s ease',
  },
  buttonText: {
    color: '#004AAD',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonHover: {
    backgroundColor: '#004AAD',
    shadowOffset: { width: 0, height: 0 },
  },
  recordingCount: {
    marginTop: 20,
    fontSize: 16,
    color: '#004AAD',
  },
  recordingIndicator: {
    alignItems: 'center',
    marginBottom: 20,
  },
  recordingTime: {
    fontSize: 24,
    color: '#F44336',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#004AAD',
  },
  modalInput: {
    height: 45,
    width: '80%',
    borderColor: '#004AAD',
    borderWidth: 1,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
});
