import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F4F9',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 20,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#004AAD',
    marginTop: 40,
  },
  searchInput: {
    height: 45,
    width: '100%',
    borderColor: '#004AAD',
    borderWidth: 1.5,
    paddingHorizontal: 10,
    marginBottom: 20,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  listContainer: {
    flex: 1,
    width: '100%',
  },
  row: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    backgroundColor: '#E6F7FF',
  },
  name: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#004AAD',
    marginBottom: 4,
  },
  details: {
    fontSize: 12,
    color: '#555',
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    justifyContent: 'space-between',
    width: '50%',
  },
  startButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    width: '80%',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  stopButton: {
    backgroundColor: '#FF5722',
    padding: 15,
    width: '80%',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#004AAD',
    marginBottom: 20,
  },
  modalInput: {
    height: 50,
    borderColor: '#004AAD',
    borderWidth: 1.5,
    borderRadius: 8,
    backgroundColor: '#fff',
    width: '80%',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  menu: {
    position: 'absolute',
    top: 60, 
    right: 20, 
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5, 
    zIndex: 10,
  },
  menuItem: {
    fontSize: 16,
    color: '#004AAD',
    fontWeight: '500',
    paddingVertical:6 ,
    paddingHorizontal: 10,
  },
  
});
