import { StyleSheet } from 'react-native'; 

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F4F9',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 20,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#004AAD',
    marginBottom: 20,
    marginTop: 40,
  },
  searchInput: {
    height: 45,
    width: '100%',
    borderColor: '#004AAD',
    borderWidth: 1.5,
    paddingHorizontal: 10,
    marginBottom: 20,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  listContainer: {
    flex: 1, 
    width: '100%', 
  },
  row: {
    flexDirection: 'column',  
    justifyContent: 'flex-start',
    alignItems: 'flex-start', 
    marginBottom: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    backgroundColor: '#E6F7FF',
  },
  name: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#004AAD',
    flex: 2,
    marginRight: 8,
    marginBottom: 4,  
  },
  details: {
    fontSize: 12,
    color: '#555',
    flex: 3,
    marginLeft: 10,
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,  
    marginLeft: 10,
    marginBottom: 5,
    justifyContent: 'space-between',  
    width: '20%',  
  },
  icon: {
    marginRight: 15,  
  },
  buttonText: {
    color: '#004AAD',
    fontSize: 16,
    fontWeight: 'bold',
  },
  startButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    width: '80%',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  stopButton: {
    backgroundColor: '#F44336',
    padding: 15,
    width: '80%',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  recordingTime: {
    fontSize: 24,
    color: '#F44336',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 15,
  },
  modalInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 10,
    width: '80%',
    marginBottom: 20,
  },
});
